version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:18.16.0  # Use a Node.js Docker image
    steps:
      - checkout                # Check out the code from GitHub
      - run:
          name: Install Dependencies
          command: npm install  # Install project dependencies
      - run:
          name: Run Tests
          command: npm test    # Run the test suite
      - run:
          name: Greeting
          command: echo "Hello, Ali Kumail! Your CI/CD pipeline is running successfully. 🚀"
